language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pablofreire6/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pablofreire6/docker-react npm run test
